// Catálogo BRAAMOD (121 productos). Edita aquí nombres, descripciones y precios.
const productos = {
        mujer: [
          {
            nombre: "Chanel N°5",
            desc: "Es el perfume más famoso del mundo. Creado en 1921 por Ernest Beaux para Coco Chanel, revolucionó la perfumería al ser el primer bouquet floral con un uso intenso de aldehídos, que dan un toque jabonoso y limpio.",
            precioAnterior: "$127.000",
            precioPromocion: "$90.000",
            tipo: "floral",
            img: "imagenes/mujer/mujer12.webp",
          },
          {
            nombre: "Chanel Coco Mademoiselle",
            desc: "Un chipre floral elegante y moderno, con notas de naranja, jazmín y pachulí. Un ícono absoluto entre las fragancias femeninas más reconocidas del mundo.",
            precioAnterior: "$135.000",
            precioPromocion: "$90.000",
            tipo: "floral",
            img: "imagenes/mujer/mujer22.webp",
          },
          {
            nombre: "Dior J'Adore",
            desc: "El floral más icónico de Dior: ylang-ylang, rosa de Damasco y jazmín sambac en una composición dorada, lujosa y profundamente femenina.",
            precioAnterior: "$145.000",
            precioPromocion: "$90.000",
            tipo: "floral",
            img: "imagenes/mujer/mujer37.webp",
          },
          {
            nombre: "Miss Dior",
            desc: "Creado originalmente en 1947 por Christian Dior. Se define como una fragancia elegante, romántica y profundamente vinculada al optimismo y al amor, combinando acordes florales, frutales y de estilo chipre.",
            precioAnterior: "$120.000",
            precioPromocion: "$90.000",
            tipo: "floral",
            img: "imagenes/mujer/mujer18.webp",
          },
          {
            nombre: "Yves Saint Laurent Black Opium",
            desc: "Fragancia floral oriental adictiva y sensual, con notas de café, vainilla y flor de azahar. Es uno de los perfumes de mujer más vendidos del mundo, perfecto para la noche.",
            precioAnterior: "$139.000",
            precioPromocion: "$90.000",
            tipo: "dulce",
            img: "imagenes/mujer/mujer21.webp",
          },
          {
            nombre: "La Vie Est Belle",
            desc: "Aroma dulce, elegante y muy duradero, diseñado para representar la alegría, la libertad y la elección de la propia felicidad.",
            precioAnterior: "$139.000",
            precioPromocion: "$90.000",
            tipo: "dulce",
            img: "imagenes/mujer/mujer20.webp",
          },
          {
            nombre: "Good Girl",
            desc: "Representa la dualidad de la mujer moderna: audaz y sexy, elegante y misteriosa, combinando notas luminosas de jazmín y nardos con otras oscuras e intensas de haba tonka y cacao, dentro de su característico frasco en forma de tacón de aguja.",
            precioAnterior: "$135.000",
            precioPromocion: "$90.000",
            tipo: "dulce",
            img: "imagenes/mujer/mujer14.webp",
          },
          {
            nombre: "Viktor & Rolf Flowerbomb",
            desc: "Una explosión floral oriental intensa y llamativa, con jazmín, rosa, pachulí y orquídea. Un clásico de alta rotación entre las fragancias más vendidas.",
            precioAnterior: "$138.000",
            precioPromocion: "$90.000",
            tipo: "dulce",
            img: "imagenes/mujer/mujer24.webp",
          },
          {
            nombre: "Paco Rabanne Olympéa",
            desc: "Fragancia de vainilla salada con flor de azahar y sal marina, sensual y muy popular entre las mujeres jóvenes.",
            precioAnterior: "$128.000",
            precioPromocion: "$90.000",
            tipo: "dulce",
            img: "imagenes/mujer/mujer26.webp",
          },
          {
            nombre: "Lady Million",
            desc: "Floral afrutado dorado y llamativo de Paco Rabanne, con naranja, jazmín y miel de patchouli. Lujoso, dulce y con gran proyección.",
            precioAnterior: "$132.000",
            precioPromocion: "$90.000",
            tipo: "dulce",
            img: "imagenes/mujer/mujer41.webp",
          },
          {
            nombre: "Giorgio Armani Sí",
            desc: "Chipre frutal moderno y contemporáneo, con grosella negra, notas florales y un fondo de pachulí. Representa a la mujer segura de sí misma.",
            precioAnterior: "$135.000",
            precioPromocion: "$90.000",
            tipo: "floral",
            img: "imagenes/mujer/mujer39.webp",
          },
          {
            nombre: "Scandal",
            desc: "Es una fragancia de la familia olfativa chipre floral, destacada por un aroma audaz, sensual y dulce, donde predomina la nota de miel combinada con naranja sanguina, gardenia y pachulí.",
            precioAnterior: "$135.900",
            precioPromocion: "$90.000",
            tipo: "dulce",
            img: "imagenes/mujer/mujer04.webp",
          },
          {
            nombre: "Versace Bright Crystal",
            desc: "Floral afrutado fresco y delicado, con granada, peonía y ámbar. Uno de los perfumes femeninos más vendidos de Versace por su versatilidad.",
            precioAnterior: "$126.000",
            precioPromocion: "$90.000",
            tipo: "floral",
            img: "imagenes/mujer/mujer42.webp",
          },
          {
            nombre: "Dior Joy",
            desc: "Floral fresco y luminoso creado para representar la felicidad, con rosa de mayo, jazmín sambac y bergamota de Calabria.",
            precioAnterior: "$142.000",
            precioPromocion: "$90.000",
            tipo: "floral",
            img: "imagenes/mujer/mujer38.webp",
          },
          {
            nombre: "Gucci Bloom",
            desc: "Floral blanco intenso y natural, con jazmín, tuberosa y jazmín sambac. Uno de los lanzamientos más exitosos de la marca.",
            precioAnterior: "$130.000",
            precioPromocion: "$90.000",
            tipo: "floral",
            img: "imagenes/mujer/mujer27.webp",
          },
          {
            nombre: "Chanel Chance",
            desc: "Floral afrutado juguetón y optimista, con notas de piña, jazmín y pachulí ámbar. Representa la espontaneidad y frescura de la mujer Chanel moderna.",
            precioAnterior: "$140.000",
            precioPromocion: "$90.000",
            tipo: "floral",
            img: "imagenes/mujer/mujer36.webp",
          },
          {
            nombre: "Carolina Herrera CH",
            desc: "Clásico chipre floral de Carolina Herrera, elegante y atemporal, con notas de mandarina, jazmín y pachulí. Un ícono de la perfumería femenina.",
            precioAnterior: "$128.000",
            precioPromocion: "$90.000",
            tipo: "floral",
            img: "imagenes/mujer/mujer35.webp",
          },
          {
            nombre: "Burberry Her",
            desc: "Fragancia frutal londinense, juvenil y fresca, con frambuesa, moras, jazmín y vainilla. Furor en redes sociales por su icónico frasco rojo.",
            precioAnterior: "$120.000",
            precioPromocion: "$90.000",
            tipo: "dulce",
            img: "imagenes/mujer/mujer28.webp",
          },
          {
            nombre: "Ariana Grande Cloud",
            desc: "Fragancia gourmand y aireada de Ariana Grande, con notas de lavanda, coco cremoso y praliné. Dulce, suave y muy reconocible en su frasco en forma de nube.",
            precioAnterior: "$126.000",
            precioPromocion: "$90.000",
            tipo: "dulce",
            img: "imagenes/mujer/mujer31.webp",
          },
          {
            nombre: "Ariana Grande Thank U, Next",
            desc: "Es un perfume de la familia olfativa floral frutal gourmand. Salida: frambuesa jugosa y pera fresca.",
            precioAnterior: "$125.900",
            precioPromocion: "$90.000",
            tipo: "dulce",
            img: "imagenes/mujer/mujer07.webp",
          },
          {
            nombre: "Victoria's Secret Bombshell",
            desc: "Fragancia de la familia olfativa floral frutal, con notas de salida de maracuyá, lichi y piña; notas de corazón de orquídea, fresia y rosa; y notas de fondo de almizcle, ámbar y madera.",
            precioAnterior: "$129.000",
            precioPromocion: "$90.000",
            tipo: "floral",
            img: "imagenes/mujer/mujer02.webp",
          },
          {
            nombre: "Moschino Toy 2",
            desc: "Floral blanco moderno y adictivo, con pera, jazmín y almizcle limpio. Frasco icónico en forma de osito, dulce sin empalagar.",
            precioAnterior: "$133.000",
            precioPromocion: "$90.000",
            tipo: "floral",
            img: "imagenes/mujer/mujer43.webp",
          },
          {
            nombre: "Juicy Couture Viva La Juicy",
            desc: "Oriental afrutado dulce y extrovertido, con mandarina, mermelada de moras y vainilla. Fresco, juvenil y de gran fijación.",
            precioAnterior: "$124.000",
            precioPromocion: "$90.000",
            tipo: "dulce",
            img: "imagenes/mujer/mujer44.webp",
          },
          {
            nombre: "Good Girl Supreme",
            desc: "Versión más intensa y dorada de Good Girl, con jazmín, tuberosa y haba tonka. Mantiene la dualidad luminosa y oscura del original pero con mayor proyección.",
            precioAnterior: "$138.000",
            precioPromocion: "$90.000",
            tipo: "dulce",
            img: "imagenes/mujer/mujer34.webp",
          },
          {
            nombre: "Giorgio Armani My Way",
            desc: "Fragancia floral blanca y cálida inspirada en la libertad y la aventura, con azahar, jazmín, tuberosa y un fondo de cedro. Tendencia fuerte en los últimos años.",
            precioAnterior: "$129.000",
            precioPromocion: "$90.000",
            tipo: "floral",
            img: "imagenes/mujer/mujer23.webp",
          },
          {
            nombre: "Shalimar",
            desc: "Es el primer perfume ambarino y oriental de la historia. Creado en 1925 e inspirado en la legendaria historia de amor del Taj Mahal, combina notas de bergamota, iris, rosa y una sobredosis de vainilla para ofrecer una estela profunda, sensual y eterna.",
            precioAnterior: "$118.000",
            precioPromocion: "$90.000",
            tipo: "dulce",
            img: "imagenes/mujer/mujer09.webp",
          },
          {
            nombre: "Dolce & Gabbana Light Blue",
            desc: "Es una fragancia icónica, conocida por su carácter chispeante, limpio y veraniego. Notas de salida (frescas y frutales): limón siciliano, manzana Granny Smith, cedro y campanilla.",
            precioAnterior: "$115.000",
            precioPromocion: "$90.000",
            tipo: "floral",
            img: "imagenes/mujer/mujer08.webp",
          },
          {
            nombre: "Flower by Kenzo",
            desc: "Floral atalcado para mujer. Creado en el año 2000, mezcla notas de rosa de Bulgaria, violeta, mandarina, vainilla y almizcles blancos, creando un aroma limpio, cálido y suave que evoca la sensación de talco de bebé.",
            precioAnterior: "$122.000",
            precioPromocion: "$90.000",
            tipo: "floral",
            img: "imagenes/mujer/mujer16.webp",
          },
          {
            nombre: "Dolce & Gabbana The Only One",
            desc: "Perfume femenino de la familia olfativa ámbar vainilla. Destaca por su mezcla única y sofisticada de violeta y café, creando un aroma dulce, atalcado y muy envolvente.",
            precioAnterior: "$156.900",
            precioPromocion: "$90.000",
            tipo: "dulce",
            img: "imagenes/mujer/mujer05.webp",
          },
          {
            nombre: "Narciso Rodriguez For Her",
            desc: "Perfume almizclado y sensual, minimalista pero muy reconocible sobre la piel, con notas de almizcle, ámbar y vainilla.",
            precioAnterior: "$125.000",
            precioPromocion: "$90.000",
            tipo: "dulce",
            img: "imagenes/mujer/mujer25.webp",
          },
          {
            nombre: "Prada Paradoxe",
            desc: "Floral ambarino suave y adictivo, con jazmín, ámbar y algodón almizclado. Una de las fragancias en crecimiento más rápido del mercado.",
            precioAnterior: "$134.000",
            precioPromocion: "$90.000",
            tipo: "floral",
            img: "imagenes/mujer/mujer30.webp",
          },
          {
            nombre: "Mugler Angel",
            desc: "El perfume que inventó la familia gourmand: praliné, chocolate y pachulí sobre un fondo estelar. Intenso, adictivo y absolutamente único.",
            precioAnterior: "$140.000",
            precioPromocion: "$90.000",
            tipo: "dulce",
            img: "imagenes/mujer/mujer45.webp",
          },
          {
            nombre: "Very Good Girl",
            desc: "Es una fragancia de la familia olfativa floral frutal para mujeres, lanzada en 2021. Presentada en su icónico frasco con forma de tacón de aguja en color rojo brillante, redefine la dualidad de la feminidad moderna con un aroma osado, divertido y muy seductor.",
            precioAnterior: "$129.000",
            precioPromocion: "$90.000",
            tipo: "floral",
            img: "imagenes/mujer/mujer17.webp",
          },
          {
            nombre: "Black XS",
            desc: "Se define como un aroma audaz, intenso, rebelde y profundamente sensual, pensado para la noche y los climas cálidos.",
            precioAnterior: "$115.000",
            precioPromocion: "$90.000",
            tipo: "dulce",
            img: "imagenes/mujer/mujer13.webp",
          },
          {
            nombre: "My Burberry Blush",
            desc: "Floral londinense delicado y romántico, con peonía, freesia y geranio sobre un fondo de almizcle suave. La versión más femenina y rosada de la línea Burberry.",
            precioAnterior: "$124.000",
            precioPromocion: "$90.000",
            tipo: "floral",
            img: "imagenes/mujer/mujer32.webp",
          },
          {
            nombre: "Bvlgari Omnia Crystalline",
            desc: "Floral acuático cristalino y luminoso, con loto, bambú y almizcle blanco. Fresco, minimalista y perfecto para el uso diario.",
            precioAnterior: "$122.000",
            precioPromocion: "$90.000",
            tipo: "floral",
            img: "imagenes/mujer/mujer33.webp",
          },
          {
            nombre: "Paco Rabanne Olympéa Aqua",
            desc: "Versión fresca y acuática de Olympéa, con notas marinas y flor de azahar sobre un fondo salado de vainilla. Ideal para el día y climas cálidos.",
            precioAnterior: "$130.000",
            precioPromocion: "$90.000",
            tipo: "floral",
            img: "imagenes/mujer/mujer40.webp",
          },
          {
            nombre: "Aqua Allegoria",
            desc: "Es una colección de perfumes femeninos frescos y alegres que rinde homenaje a la naturaleza. Estas fragancias combinan notas cítricas, florales y frutales con materias primas de alta calidad, ofreciendo aromas luminosos, elegantes y perfectos para el uso diario.",
            precioAnterior: "$115.000",
            precioPromocion: "$90.000",
            tipo: "floral",
            img: "imagenes/mujer/mujer11.webp",
          },
          {
            nombre: "Coco Chanel Girl",
            desc: "Es un perfume de mujer ámbar floral, fresco y sensual. Combina notas de salida de naranja y mandarina con un corazón de jazmín y rosa, sobre un fondo cálido de pachulí y vainilla. Representa a una mujer libre, audaz, elegante y moderna.",
            precioAnterior: "$128.000",
            precioPromocion: "$90.000",
            tipo: "floral",
            img: "imagenes/mujer/mujer10.webp",
          },
          {
            nombre: "Botica 214",
            desc: "Eau de Parfum de alta sofisticación que combina contrastes naturales, notas amaderadas y frescura intensa, inspirada en viajes y descubrimientos globales.",
            precioAnterior: "$115.000",
            precioPromocion: "$90.000",
            tipo: "amaderado",
            img: "imagenes/mujer/mujer19.webp",
          },
          {
            nombre: "Rome Melancholia",
            desc: "Combina una salida fresca de cítricos y especias con un corazón cremoso de coco y lavanda, cerrando con un fondo cálido de maderas y ámbar.",
            precioAnterior: "$118.000",
            precioPromocion: "$90.000",
            tipo: "amaderado",
            img: "imagenes/mujer/mujer15.webp",
          },
          {
            nombre: "Feeling Chic",
            desc: "Fragancia femenina fresca y vibrante, con notas de manzana verde, pepino y limón.",
            precioAnterior: "$129.900",
            precioPromocion: "$90.000",
            tipo: "floral",
            img: "imagenes/mujer/mujer03.webp",
          },
          {
            nombre: "Lucky 7 Passion",
            desc: "Perfume para mujer de la familia dulce, frutal y floral. Ejemplo: floral, dulce y elegante.",
            precioAnterior: "$119.000",
            precioPromocion: "$90.000",
            tipo: "dulce",
            img: "imagenes/mujer/mujer01.webp",
          },
        ],
        hombre: [
          {
            nombre: "Sauvage",
            desc: "Mezcla notas cítricas chispeantes con un fondo de maderas ambarinas y especias, inspirada en los grandes espacios abiertos bajo un cielo nocturno. Su estela es intensa, seductora y de gran fijación en la piel.",
            precioAnterior: "$178.000",
            precioPromocion: "$90.000",
            tipo: "amaderado",
            img: "imagenes/hombre/hombre20.webp",
          },
          {
            nombre: "Bleu de Chanel",
            desc: "Fragancia amaderada y aromática para hombre que representa la libertad y la elegancia moderna.",
            precioAnterior: "$117.000",
            precioPromocion: "$90.000",
            tipo: "amaderado",
            img: "imagenes/hombre/hombre16.webp",
          },
          {
            nombre: "1 Million",
            desc: "Destaca por un aroma audaz, dulce y seductor, con notas de menta, mandarina, canela y cuero. Ideal para la noche y climas templados o fríos.",
            precioAnterior: "$148.000",
            precioPromocion: "$90.000",
            tipo: "dulce",
            img: "imagenes/hombre/hombre19.webp",
          },
          {
            nombre: "Giorgio Armani Acqua di Giò",
            desc: "Fragancia acuática y aromática, fresca desde 1996 y referencia mundial de las notas marinas, con cítricos, romero y salvia.",
            precioAnterior: "$125.000",
            precioPromocion: "$90.000",
            tipo: "floral",
            img: "imagenes/hombre/hombre21.webp",
          },
          {
            nombre: "Creed Aventus",
            desc: "Afrutado amaderado potente e icónico, con notas de piña, abedul y almizcle. Sinónimo de éxito y prestigio en el mundo de la perfumería.",
            precioAnterior: "$155.000",
            precioPromocion: "$90.000",
            tipo: "amaderado",
            img: "imagenes/hombre/hombre23.webp",
          },
          {
            nombre: "Jean Paul Gaultier Le Male",
            desc: "Mezcla notas frescas de menta y lavanda con un fondo cálido y dulce de vainilla.",
            precioAnterior: "$129.000",
            precioPromocion: "$90.000",
            tipo: "dulce",
            img: "imagenes/hombre/hombre15.webp",
          },
          {
            nombre: "Invictus",
            desc: "Encarna la victoria, la energía y el dinamismo mediante un choque entre la frescura marina y una sensualidad amaderada y cálida.",
            precioAnterior: "$138.000",
            precioPromocion: "$90.000",
            tipo: "amaderado",
            img: "imagenes/hombre/hombre07.webp",
          },
          {
            nombre: "Versace Eros",
            desc: "Destaca por ser un aroma intenso, dulce y muy sensual, diseñado para hombres seguros de sí mismos que buscan acaparar miradas.",
            precioAnterior: "$147.000",
            precioPromocion: "$90.000",
            tipo: "dulce",
            img: "imagenes/hombre/hombre17.webp",
          },
          {
            nombre: "Hermès Terre d'Hermès",
            desc: "Amaderado mineral elegante y sofisticado, con pomelo, vetiver y pimienta. Un clásico atemporal de alta gama.",
            precioAnterior: "$140.000",
            precioPromocion: "$90.000",
            tipo: "amaderado",
            img: "imagenes/hombre/hombre29.webp",
          },
          {
            nombre: "Fahrenheit",
            desc: "Mezcla notas de mandarina de Sicilia, violeta, cuero y maderas cálidas, creando un aroma inconfundible, maduro y con un toque sutilmente amaderado y petroleado muy característico.",
            precioAnterior: "$119.000",
            precioPromocion: "$90.000",
            tipo: "amaderado",
            img: "imagenes/hombre/hombre13.webp",
          },
          {
            nombre: "Hugo Boss Bottled",
            desc: "Amaderado especiado, versátil y de excelente calidad, con manzana, canela y sándalo. Uno de los perfumes masculinos más vendidos del mundo.",
            precioAnterior: "$118.000",
            precioPromocion: "$90.000",
            tipo: "amaderado",
            img: "imagenes/hombre/hombre24.webp",
          },
          {
            nombre: "Maison Francis Kurkdjian Baccarat Rouge 540",
            desc: "Fragancia unisex cálida y adictiva, con jazmín, azafrán y madera de ámbar. Una de las fragancias de nicho más vendidas y reconocibles del mundo.",
            precioAnterior: "$145.000",
            precioPromocion: "$90.000",
            tipo: "amaderado",
            img: "imagenes/hombre/hombre22.webp",
          },
          {
            nombre: "Azzaro The Most Wanted",
            desc: "Vainilla especiada y cálida, con jengibre, cardamomo y vainilla bourbon. Ha arrasado en ventas durante los últimos años.",
            precioAnterior: "$128.000",
            precioPromocion: "$90.000",
            tipo: "dulce",
            img: "imagenes/hombre/hombre25.webp",
          },
          {
            nombre: "Giorgio Armani Stronger With You Intensely",
            desc: "Especiado y dulce, envolvente y cálido, con cardamomo, avellana y vainilla. Muy popular entre las generaciones más jóvenes.",
            precioAnterior: "$122.000",
            precioPromocion: "$90.000",
            tipo: "dulce",
            img: "imagenes/hombre/hombre26.webp",
          },
          {
            nombre: "Yves Saint Laurent Y",
            desc: "Aromático fougère fresco y moderno, con manzana, salvia y geranio. Pensado para el hombre ambicioso y seguro de sí mismo.",
            precioAnterior: "$126.000",
            precioPromocion: "$90.000",
            tipo: "amaderado",
            img: "imagenes/hombre/hombre27.webp",
          },
          {
            nombre: "Jean Paul Gaultier Le Beau",
            desc: "Amaderado floral cálido y tropical, hermano del icónico Le Male, con coco, haba tonka y madera.",
            precioAnterior: "$130.000",
            precioPromocion: "$90.000",
            tipo: "amaderado",
            img: "imagenes/hombre/hombre28.webp",
          },
          {
            nombre: "Parfums de Marly Layton",
            desc: "Amaderado especiado de lujo, con manzana, lavanda y vainilla sobre un fondo de almizcle y ámbar. Uno de los perfumes de nicho más deseados actualmente.",
            precioAnterior: "$155.000",
            precioPromocion: "$90.000",
            tipo: "dulce",
            img: "imagenes/hombre/hombre33.webp",
          },
          {
            nombre: "Acqua di Parma Colonia",
            desc: "Cítrico clásico e italiano, con limón, bergamota y lavanda. Referencia de elegancia atemporal desde hace décadas.",
            precioAnterior: "$132.000",
            precioPromocion: "$90.000",
            tipo: "floral",
            img: "imagenes/hombre/hombre30.webp",
          },
          {
            nombre: "Calvin Klein CK One",
            desc: "Cítrico y fresco, de origen unisex pero muy popular entre hombres jóvenes. Ligero, versátil y perfecto para el uso diario.",
            precioAnterior: "$105.000",
            precioPromocion: "$90.000",
            tipo: "floral",
            img: "imagenes/hombre/hombre39.webp",
          },
          {
            nombre: "212 Men NYC",
            desc: "Huele a césped recién cortado, hojas de cítricos, jengibre y especias verdes, con un fondo cálido de sándalo e incienso.",
            precioAnterior: "$139.000",
            precioPromocion: "$90.000",
            tipo: "amaderado",
            img: "imagenes/hombre/hombre05.webp",
          },
          {
            nombre: "Invictus Legend",
            desc: "Amaderado aromático intenso, con lavanda, pachulí y vainilla de Madagascar. Una evolución más madura y potente del Invictus original.",
            precioAnterior: "$138.000",
            precioPromocion: "$90.000",
            tipo: "amaderado",
            img: "imagenes/hombre/hombre44.webp",
          },
          {
            nombre: "One Million Lucky",
            desc: "Versión más fresca y frutal de One Million, con manzana verde y notas amaderadas. Juvenil, dulce y de gran proyección.",
            precioAnterior: "$140.000",
            precioPromocion: "$90.000",
            tipo: "dulce",
            img: "imagenes/hombre/hombre43.webp",
          },
          {
            nombre: "Paco Rabanne Phantom",
            desc: "Fougère futurista con lavanda, avellana y almizcle. Innovador, fresco y con una firma olfativa muy distinta a lo tradicional.",
            precioAnterior: "$130.000",
            precioPromocion: "$90.000",
            tipo: "amaderado",
            img: "imagenes/hombre/hombre45.webp",
          },
          {
            nombre: "Hugo Boss Bottled Night",
            desc: "Versión nocturna de Bottled, más oscura y amaderada, con pimienta negra, lavanda y pachulí. Pensada para ocasiones formales de noche.",
            precioAnterior: "$122.000",
            precioPromocion: "$90.000",
            tipo: "amaderado",
            img: "imagenes/hombre/hombre34.webp",
          },
          {
            nombre: "Hugo Boss Bottled Tonic",
            desc: "Fresca y cítrica, con notas de cedro y vetiver. La versión más ligera y veraniega de la línea Bottled.",
            precioAnterior: "$120.000",
            precioPromocion: "$90.000",
            tipo: "floral",
            img: "imagenes/hombre/hombre35.webp",
          },
          {
            nombre: "Hugo Boss The Scent",
            desc: "Oriental especiado y seductor, con jengibre, lavanda y ámbar de maple. Una de las fragancias más sensuales de la casa Hugo Boss.",
            precioAnterior: "$128.000",
            precioPromocion: "$90.000",
            tipo: "dulce",
            img: "imagenes/hombre/hombre36.webp",
          },
          {
            nombre: "Bvlgari Man In Black",
            desc: "Oriental amaderado intenso, con especias, ron y cuero. Potente, cálido y de gran carácter para la noche.",
            precioAnterior: "$135.000",
            precioPromocion: "$90.000",
            tipo: "amaderado",
            img: "imagenes/hombre/hombre37.webp",
          },
          {
            nombre: "Bvlgari Aqva",
            desc: "Acuático amaderado inspirado en el mar Mediterráneo, con notas marinas y madera de cedro. Fresco, limpio y elegante.",
            precioAnterior: "$128.000",
            precioPromocion: "$90.000",
            tipo: "amaderado",
            img: "imagenes/hombre/hombre38.webp",
          },
          {
            nombre: "Dior Homme Intense",
            desc: "Amaderado floral con iris, cuero y vetiver. Elegante, sofisticado y con una identidad muy marcada dentro de la perfumería masculina.",
            precioAnterior: "$148.000",
            precioPromocion: "$90.000",
            tipo: "amaderado",
            img: "imagenes/hombre/hombre41.webp",
          },
          {
            nombre: "Creed Silver Mountain Water",
            desc: "Fresco y verde, con té verde, bergamota y almizcle. Un clásico de Creed asociado a la elegancia discreta y el estilo de vida activo.",
            precioAnterior: "$150.000",
            precioPromocion: "$90.000",
            tipo: "amaderado",
            img: "imagenes/hombre/hombre40.webp",
          },
          {
            nombre: "Dolce & Gabbana The One",
            desc: "Oriental especiado cálido, con tabaco, cardamomo y ámbar. Sofisticado y pensado para el hombre maduro y seguro de sí mismo.",
            precioAnterior: "$132.000",
            precioPromocion: "$90.000",
            tipo: "dulce",
            img: "imagenes/hombre/hombre42.webp",
          },
          {
            nombre: "Dolce & Gabbana Light Blue Forever",
            desc: "Destaca por una explosión ultra realista, jugosa y amarga de toronja (pomelo) y bergamota en la salida; matices ozónicos en el corazón y una base seca de vetiver de Java y almizcle blanco.",
            precioAnterior: "$136.000",
            precioPromocion: "$90.000",
            tipo: "floral",
            img: "imagenes/hombre/hombre12.webp",
          },
          {
            nombre: "Antonio Banderas Icon",
            desc: "Amaderado aromático elegante y masculino, con bergamota, cardamomo y vetiver. Versátil para el día a día y de buena fijación.",
            precioAnterior: "$110.000",
            precioPromocion: "$90.000",
            tipo: "amaderado",
            img: "imagenes/hombre/hombre31.webp",
          },
          {
            nombre: "Antonio Banderas Blue Seduction",
            desc: "Fresco y acuático, con notas cítricas y un fondo amaderado suave. Ideal para el uso diario por su frescura duradera.",
            precioAnterior: "$95.000",
            precioPromocion: "$90.000",
            tipo: "amaderado",
            img: "imagenes/hombre/hombre32.webp",
          },
          {
            nombre: "Valentino Uomo",
            desc: "Es un perfume para hombre de estilo clásico y elegante. Tiene un aroma dulce y amaderado, con notas de chocolate, café y avellana. Es ideal para usar en días fríos.",
            precioAnterior: "$129.000",
            precioPromocion: "$90.000",
            tipo: "dulce",
            img: "imagenes/hombre/hombre04.webp",
          },
          {
            nombre: "Valentino Intense",
            desc: "Destaca por su aroma profundo, cómodo y ligeramente atalcado, ideal para climas frescos y ocasiones nocturnas.",
            precioAnterior: "$125.000",
            precioPromocion: "$90.000",
            tipo: "amaderado",
            img: "imagenes/hombre/hombre11.webp",
          },
          {
            nombre: "Versace Pour Homme",
            desc: "Este aroma de la familia aromática Fougère evoca la brisa del mar Mediterráneo con un estilo limpio, elegante y muy versátil.",
            precioAnterior: "$125.000",
            precioPromocion: "$90.000",
            tipo: "floral",
            img: "imagenes/hombre/hombre10.webp",
          },
          {
            nombre: "Nautica Voyage",
            desc: "Destaca por su aroma limpio, fresco y frutal que evoca la sensación de salir de la ducha.",
            precioAnterior: "$115.000",
            precioPromocion: "$90.000",
            tipo: "floral",
            img: "imagenes/hombre/hombre08.webp",
          },
          {
            nombre: "Eternity",
            desc: "Destaca por su frescura limpia, un estilo varonil y una sensación reconfortante que evoca un baño matutino. Es una fragancia versátil, elegante y segura que nunca pasa de moda.",
            precioAnterior: "$118.000",
            precioPromocion: "$90.000",
            tipo: "floral",
            img: "imagenes/hombre/hombre03.webp",
          },
          {
            nombre: "Solo Elixir",
            desc: "Combina notas balsámicas cremosas, el olíbano provocativo y la elegancia de la madera de Oud.",
            precioAnterior: "$129.000",
            precioPromocion: "$90.000",
            tipo: "amaderado",
            img: "imagenes/hombre/hombre14.webp",
          },
          {
            nombre: "Magnate Exclusive",
            desc: "Perfume masculino de alta concentración y muy larga duración, perteneciente a la familia olfativa herbal aromática con dejos orientales y de cuero. Está inspirado en el hombre exitoso, moderno y seguro de sí mismo que disfruta de experiencias exclusivas.",
            precioAnterior: "$100.000",
            precioPromocion: "$90.000",
            tipo: "amaderado",
            img: "imagenes/hombre/hombre18.webp",
          },
          {
            nombre: "Clash",
            desc: "Es un perfume masculino de la familia olfativa aromática acuática (Fougère acuosa), creado por el perfumista Dominique Ropion. Ofrece un frescor potente y moderno, diseñado para el uso diario, el trabajo o la actividad física.",
            precioAnterior: "$119.000",
            precioPromocion: "$90.000",
            tipo: "amaderado",
            img: "imagenes/hombre/hombre01.webp",
          },

        ],
        economicos: [
          {
            nombre: "Envase gris",
            desc: "Elige tu tamaño, elige tu esencia. Cada fragancia de BRAAMOD está disponible en presentación de 50 ml y 100 ml, en el mismo envase facetado que ves en nuestras fotos. La diferencia está en la duración que quieres llevar contigo. El frasco es solo el punto de partida: dentro va la fragancia que tú elijas de nuestro catálogo. Selecciona el aroma que más se ajuste a tu personalidad y nosotros lo preparamos en el tamaño que prefieras.",
            esEconomico: true,
            precio50: "$25.000",
            precio100: "$45.000",
            tipo: "dulce",
            img: "imagenes/economicos/economico01.webp",
          },
          {
            nombre: "Envase verde",
            desc: "Elige tu tamaño, elige tu esencia. Cada fragancia de BRAAMOD está disponible en presentación de 50 ml y 100 ml, en el mismo envase facetado que ves en nuestras fotos. La diferencia está en la duración que quieres llevar contigo. El frasco es solo el punto de partida: dentro va la fragancia que tú elijas de nuestro catálogo. Selecciona el aroma que más se ajuste a tu personalidad y nosotros lo preparamos en el tamaño que prefieras.",
            esEconomico: true,
            precio50: "$25.000",
            precio100: "$45.000",
            tipo: "floral",
            img: "imagenes/economicos/economico02.webp",
          },
          {
            nombre: "Envase azul",
            desc: "Elige tu tamaño, elige tu esencia. Cada fragancia de BRAAMOD está disponible en presentación de 50 ml y 100 ml, en el mismo envase facetado que ves en nuestras fotos. La diferencia está en la duración que quieres llevar contigo. El frasco es solo el punto de partida: dentro va la fragancia que tú elijas de nuestro catálogo. Selecciona el aroma que más se ajuste a tu personalidad y nosotros lo preparamos en el tamaño que prefieras.",
            esEconomico: true,
            precio50: "$25.000",
            precio100: "$45.000",
            tipo: "amaderado",
            img: "imagenes/economicos/economico03.webp",
          },
          {
            nombre: "Envase negro",
            desc: "Elige tu tamaño, elige tu esencia. Cada fragancia de BRAAMOD está disponible en presentación de 50 ml y 100 ml, en el mismo envase facetado que ves en nuestras fotos. La diferencia está en la duración que quieres llevar contigo. El frasco es solo el punto de partida: dentro va la fragancia que tú elijas de nuestro catálogo. Selecciona el aroma que más se ajuste a tu personalidad y nosotros lo preparamos en el tamaño que prefieras.",
            esEconomico: true,
            precio50: "$25.000",
            precio100: "$45.000",
            tipo: "amaderado",
            img: "imagenes/economicos/economico04.webp",
          },
          {
            nombre: "Envase rojo",
            desc: "Elige tu tamaño, elige tu esencia. Cada fragancia de BRAAMOD está disponible en presentación de 50 ml y 100 ml, en el mismo envase facetado que ves en nuestras fotos. La diferencia está en la duración que quieres llevar contigo. El frasco es solo el punto de partida: dentro va la fragancia que tú elijas de nuestro catálogo. Selecciona el aroma que más se ajuste a tu personalidad y nosotros lo preparamos en el tamaño que prefieras.",
            esEconomico: true,
            precio50: "$25.000",
            precio100: "$45.000",
            tipo: "dulce",
            img: "imagenes/economicos/economico05.webp",
          },
          {
            nombre: "Envase dorado",
            desc: "Elige tu tamaño, elige tu esencia. Cada fragancia de BRAAMOD está disponible en presentación de 50 ml y 100 ml, en el mismo envase facetado que ves en nuestras fotos. La diferencia está en la duración que quieres llevar contigo. El frasco es solo el punto de partida: dentro va la fragancia que tú elijas de nuestro catálogo. Selecciona el aroma que más se ajuste a tu personalidad y nosotros lo preparamos en el tamaño que prefieras.",
            esEconomico: true,
            precio50: "$25.000",
            precio100: "$45.000",
            tipo: "dulce",
            img: "imagenes/economicos/economico06.webp",
          },
        ],
        "arabes-mujer": [
          {
            nombre: "Yara",
            desc: "Perfume árabe de mujer de la casa Lattafa, floral dulce y envolvente, con notas de vainilla, flor de azahar y almizcle. Su frasco rosa es uno de los más buscados dentro del género árabe.",
            precioAnterior: "$125.000",
            precioPromocion: "$90.000",
            tipo: "dulce",
            img: "imagenes/arabes-mujer/arabesmujer01.webp",
          },
          {
            nombre: "Club De Nuit Woman",
            desc: "Versión femenina del perfume árabe más vendido del mundo (Armaf). Chipre floral con gran fijación y una estela que dura todo el día.",
            precioAnterior: "$130.000",
            precioPromocion: "$90.000",
            tipo: "floral",
            img: "imagenes/arabes-mujer/arabesmujer10.webp",
          },
          {
            nombre: "Hawas For Her",
            desc: "Perfume árabe de mujer de Rasasi que mezcla notas dulces, frutales y florales con un toque elegante. Tiene una gran fijación en la piel y una estela muy potente que deja huella.",
            precioAnterior: "$119.000",
            precioPromocion: "$90.000",
            tipo: "floral",
            img: "imagenes/arabes-mujer/arabesmujer05.webp",
          },
          {
            nombre: "Yara Candy",
            desc: "Versión gourmand de Yara, más dulce y golosa, con notas de caramelo y flores blancas sobre un fondo cálido de almizcle.",
            precioAnterior: "$128.000",
            precioPromocion: "$90.000",
            tipo: "dulce",
            img: "imagenes/arabes-mujer/arabesmujer02.webp",
          },
          {
            nombre: "Yara Moi",
            desc: "La versión más elegante y sofisticada de la línea Yara, con un floral blanco más sereno y una estela envolvente de larga duración.",
            precioAnterior: "$130.000",
            precioPromocion: "$90.000",
            tipo: "floral",
            img: "imagenes/arabes-mujer/arabesmujer03.webp",
          },
          {
            nombre: "Yara Tous",
            desc: "Edición tropical y frutal de Yara, con notas de mango y flores exóticas que le dan un toque juvenil y veraniego.",
            precioAnterior: "$126.000",
            precioPromocion: "$90.000",
            tipo: "dulce",
            img: "imagenes/arabes-mujer/arabesmujer04.webp",
          },
          {
            nombre: "9 AM Pour Femme",
            desc: "Versión femenina del icónico 9AM de Afnan, floral fresco con un toque cítrico que aligera su estela oriental.",
            precioAnterior: "$118.000",
            precioPromocion: "$90.000",
            tipo: "floral",
            img: "imagenes/arabes-mujer/arabesmujer09.webp",
          },
          {
            nombre: "Fakhar Rose",
            desc: "Fragancia árabe floral con el sello inconfundible de la rosa, combinada con especias suaves y un fondo amaderado sutil.",
            precioAnterior: "$124.000",
            precioPromocion: "$90.000",
            tipo: "floral",
            img: "imagenes/arabes-mujer/arabesmujer07.webp",
          },
          {
            nombre: "Haya",
            desc: "Perfume árabe de mujer de Rasasi, floral oriental delicado, pensado para una feminidad discreta y elegante.",
            precioAnterior: "$120.000",
            precioPromocion: "$90.000",
            tipo: "floral",
            img: "imagenes/arabes-mujer/arabesmujer08.webp",
          },
          {
            nombre: "Ajwad Pink",
            desc: "Floral rosado suave y femenino de Lattafa, con notas de peonía y almizcle blanco sobre un fondo delicado y cálido.",
            precioAnterior: "$122.000",
            precioPromocion: "$90.000",
            tipo: "floral",
            img: "imagenes/arabes-mujer/arabesmujer06.webp",
          },
        ],
        "arabes-hombre": [
          {
            nombre: "Asad",
            desc: "Perfume árabe de hombre de Lattafa. Destaca por un aroma intenso, cálido y especiado, con gran proyección y fijación.",
            precioAnterior: "$135.000",
            precioPromocion: "$90.000",
            tipo: "amaderado",
            img: "imagenes/arabes-hombre/arabeshombre01.webp",
          },
          {
            nombre: "9 PM Men",
            desc: "Uno de los perfumes árabes masculinos más vendidos. Oriental vainilla especiado de gran fijación, ideal para la noche.",
            precioAnterior: "$128.000",
            precioPromocion: "$90.000",
            tipo: "dulce",
            img: "imagenes/arabes-hombre/arabeshombre08.webp",
          },
          {
            nombre: "Hawas For Him",
            desc: "Perfume árabe de hombre de Rasasi, amaderado oriental potente, con una estela intensa y muy duradera.",
            precioAnterior: "$122.000",
            precioPromocion: "$90.000",
            tipo: "amaderado",
            img: "imagenes/arabes-hombre/arabeshombre03.webp",
          },
          {
            nombre: "Maahir",
            desc: "Perfume árabe oriental especiado y cálido de Lattafa, con notas dulces que se mantienen firmes durante todo el día.",
            precioAnterior: "$120.000",
            precioPromocion: "$90.000",
            tipo: "dulce",
            img: "imagenes/arabes-hombre/arabeshombre06.webp",
          },
          {
            nombre: "Asad Zanzibar",
            desc: "Variante más cálida y especiada de Asad, con notas de canela y maderas orientales que la hacen ideal para la noche.",
            precioAnterior: "$137.000",
            precioPromocion: "$90.000",
            tipo: "amaderado",
            img: "imagenes/arabes-hombre/arabeshombre02.webp",
          },
          {
            nombre: "Qahwa",
            desc: "Perfume árabe de Rasasi inspirado en el café especiado, amaderado y cálido, con una estela envolvente e intensa.",
            precioAnterior: "$126.000",
            precioPromocion: "$90.000",
            tipo: "amaderado",
            img: "imagenes/arabes-hombre/arabeshombre09.webp",
          },
          {
            nombre: "Shaheen",
            desc: "Fragancia árabe de oud potente y amaderada, pensada para un hombre que busca una presencia fuerte y duradera.",
            precioAnterior: "$129.000",
            precioPromocion: "$90.000",
            tipo: "amaderado",
            img: "imagenes/arabes-hombre/arabeshombre10.webp",
          },
          {
            nombre: "Maahir (versión oscura)",
            desc: "Versión más oscura y amaderada de Maahir, con un fondo de oud y especias intensas.",
            precioAnterior: "$123.000",
            precioPromocion: "$90.000",
            tipo: "amaderado",
            img: "imagenes/arabes-hombre/arabeshombre07.webp",
          },
          {
            nombre: "Fakhar Black",
            desc: "Versión oscura de Fakhar, amaderada y de cuero, pensada para un hombre de carácter fuerte y elegante.",
            precioAnterior: "$124.000",
            precioPromocion: "$90.000",
            tipo: "amaderado",
            img: "imagenes/arabes-hombre/arabeshombre05.webp",
          },
          {
            nombre: "Ajwad",
            desc: "Oriental especiado y dulce de Lattafa, con notas de vainilla y ámbar sobre un fondo amaderado cálido.",
            precioAnterior: "$121.000",
            precioPromocion: "$90.000",
            tipo: "dulce",
            img: "imagenes/arabes-hombre/arabeshombre04.webp",
          },
        ],
        unisex: [
          {
            nombre: "Khamrah",
            desc: "Perfume unisex de la familia oriental especiada, lanzado en 2022. Destaca por su aroma dulce, cálido y avainillado con un toque de licor y especias, ideal para una estela intensa, elegante y nocturna.",
            precioAnterior: "$125.000",
            precioPromocion: "$90.000",
            tipo: "dulce",
            img: "imagenes/unisex/unisex01.webp",
          },
          {
            nombre: "Club De Nuit Intense",
            desc: "El perfume árabe unisex más vendido del mundo (Armaf). Amaderado y dulce, con una relación calidad-precio inigualable.",
            precioAnterior: "$130.000",
            precioPromocion: "$90.000",
            tipo: "amaderado",
            img: "imagenes/unisex/unisex07.webp",
          },
          {
            nombre: "Amber Rouge",
            desc: "Perfume unisex de Orientica, ambarino y dulce, presentado en un elegante estuche de lujo. Ideal para quienes buscan una fragancia cálida e intensa.",
            precioAnterior: "$140.000",
            precioPromocion: "$90.000",
            tipo: "dulce",
            img: "imagenes/unisex/unisex02.webp",
          },
          {
            nombre: "Orientica (ámbar dorado)",
            desc: "Ambarino dorado y cálido de Orientica, con un fondo envolvente de vainilla y maderas preciosas.",
            precioAnterior: "$142.000",
            precioPromocion: "$90.000",
            tipo: "dulce",
            img: "imagenes/unisex/unisex03.webp",
          },
          {
            nombre: "Club De Nuit Untold",
            desc: "Versión fresca y especiada de Club de Nuit, unisex, con una estela vibrante y moderna.",
            precioAnterior: "$132.000",
            precioPromocion: "$90.000",
            tipo: "amaderado",
            img: "imagenes/unisex/unisex08.webp",
          },
          {
            nombre: "Oud Saffron",
            desc: "Perfume unisex de Orientica con oud y azafrán, especiado y amaderado, de gran proyección y fijación en la piel.",
            precioAnterior: "$145.000",
            precioPromocion: "$90.000",
            tipo: "amaderado",
            img: "imagenes/unisex/unisex04.webp",
          },
          {
            nombre: "Bade'e Al Oud For Glory",
            desc: "Fragancia unisex de lujo con oud como protagonista, amaderada y envolvente, presentada en un exclusivo estuche.",
            precioAnterior: "$148.000",
            precioPromocion: "$90.000",
            tipo: "amaderado",
            img: "imagenes/unisex/unisex06.webp",
          },
          {
            nombre: "Amber Noir",
            desc: "Versión más oscura y misteriosa de la línea Amber de Orientica, amaderada e intensa, ideal para la noche.",
            precioAnterior: "$143.000",
            precioPromocion: "$90.000",
            tipo: "amaderado",
            img: "imagenes/unisex/unisex05.webp",
          },
          {
            nombre: "Odyssey Mandarin Sky",
            desc: "Cítrico dulce y unisex de Armaf, fresco y luminoso, ideal para el uso diario.",
            precioAnterior: "$124.000",
            precioPromocion: "$90.000",
            tipo: "dulce",
            img: "imagenes/unisex/unisex09.webp",
          },
          {
            nombre: "Nusuk Blanc",
            desc: "Fragancia unisex limpia y almizclada, fresca y elegante, pensada para dejar una estela sutil pero reconocible.",
            precioAnterior: "$121.000",
            precioPromocion: "$90.000",
            tipo: "floral",
            img: "imagenes/unisex/unisex10.webp",
          },
        ],
      };

